# Generated by Django 4.2.5 on 2023-09-05 20:15

from django.db import migrations, models
import django.db.models.deletion
import referal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=referal.models.Referal.generate_code, editable=False, max_length=8)),
                ('invite_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referal.referal')),
            ],
        ),
    ]
